### ISSUE TITLE
uv:templateId should be URI

### ISSUE THREAD

**Issue by ktk** [uduvudu/uduvudu#11]
For Linked Data reasons `uv:templateId` should be URIs, not literals

**Comment by l00mi** [comment]
oppose,

this gives the loos coupling right now.

But needs to discussed.

**Comment by ktk** [comment]
I see that for the moment but from a scaling & networking effect POV this doesn't make much sense. But agree, needs to be discussed offline.

**Comment by l00mi** [comment]
Discussions resolved that we will use URI for templateID, probably rename it to templateGroup.

Background: We do not want direct pointers from matchers to templates. So in future we will point templates and matchers to templateGroup URI.

**Comment by retog** [comment]
rather than templateGroup i would suggest #asbtractTemplate as the property pointing from the matcher to the abstract template. A concrete template implements an abstract template for a specific format/device/capabilities/etc.

**Comment by l00mi** [comment]
Sounds good, I like this better than #templateGroup.. will change also to #abstractTemplate and start using fully qualified IRIs.

**Comment by l00mi** [comment]
change is done in version 0.6
