### ISSUE TITLE
How to visualize results of a SPARQL query

### ISSUE THREAD

**Issue by giuseppefutia** [uduvudu/uduvudu#18]
Dear All,

I'd like to use Uduvudu to visualize results of a SPARQL query. I think that a possible solution is using a "CONSTRUCT" query, in order to load data in a LdpStore() on the client.

Is the only possible solution?

Thanks,

Giuseppe

**Comment by ktk** [comment]
Hi Giuseppe,

Yes I think currently that would be the way to do it. We might think about a helper function which makes it a bit nicer so one can simply provide the SPARQL query instead of URLencoding it into the code.

Anyone got a good idea on how this could look like?

**Comment by giuseppefutia** [comment]
Thank you for your answer!

Is there a method for defining more than one "start resource"? I try to explain my question in the following rows.

When I want to visualize data related to a specific resource (for example "http://dbpedia.org/resource/Barack_Obama"), I write something like:

```javascript

var  source = "http://dbpedia.org/resource/Barack_Obama";
store.graph(source, function (graph, error) {
                if (error == null) {
                    console.debug("successfully loaded "+graph.toArray().length+" triples");
                    // resource (entry for template search) is same as source in this example
                    uduvudu.process(graph, {'resource': source} , function (out) {
                        // write the result of the processing in the main div
                        $('#main').html(out);
                        });
                    } else {
                        document.getElementById('main').innerHTML =  ''
                        + '<div class="alert alert-danger">'
                        + '  <button type="button" class="close" data-dismiss="alert">&times;</button>'
                        + '  <strong>Error:</strong> '+ error +'.'
                        + '</div>';
                    };
            });

```

But, if I want to visualize data from an RDF with multiple "start resources" (for example I want to represent a list of events on a timeline, so my "start resources" are the URIs that identify the events) how can I do that?

Thank you!

**Comment by l00mi** [comment]
Hey there,

Looks like you have some amazing plans going on. I am looking forward to see what you build with Uduvudu.

So for your use-case the Uduvudu way would be to add some more to the graph before processing it by Uduvudu. Like e.g.

<timeline:rendering> <contains> <event1>.
<timeline:rendering> <contains> <event2>.
<timeline:rendering> <contains> <event3>.

Then you use the <timeline:rendering> as a start resource.

Does this make sense?
Best Michael

**Comment by l00mi** [comment]
Also, just thinking.. if you get the data through SPARQL Construct, you could add this additional triples easily by changing the query.

**Comment by giuseppefutia** [comment]
Thank you, Michael!

Your suggestion sounds good!
I'll keep you informed on our progress using uduvudu.

Best,
Giuseppe

**Comment by l00mi** [comment]
I close this for now, please make sure to keep us posted!

**Comment by giuseppefutia** [comment]
Dear Michael,

we have published our first demo within the Fusepool project, showing Trentino's events data using parts of Uduvudu: http://explorer.nexacenter.org/.

Best,

Giuseppe

**Comment by l00mi** [comment]
Thanks Giuseppe,
Perfect timing and looks impressive, I will show your example in 1h at WWW2015.it in Firenze! (,

Best,
Michael
