### ISSUE TITLE
JSFiddle Examples

### ISSUE THREAD

**Issue by ktk** [uduvudu/uduvudu#9]
Provide a JSFiddle which shows Uduvudu in action.

Base: http://jsfiddle.net/Lw6frtqq/11/

**Comment by ktk** [comment]
Updated version: http://jsfiddle.net/j862exfp/1/ by @l00mi but runs into CORS issues now...

**Comment by l00mi** [comment]
http://jsfiddle.net/j862exfp/8/ getting source from github circumvents CORS

**Comment by ktk** [comment]
Very nice thanks!

**Comment by l00mi** [comment]
http://jsfiddle.net/sgfoy16b/5/
